Handle user data not existing at all in metadata
Right now if there's no user data we're getting a no method exception:

[2016-02-01T20:27:33+00:00] DEBUG: Plugin EC2 threw #<NoMethodError: undefined method `encoding' for nil:NilClass>
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/plugins/ec2.rb:79:in `block (2 levels) in <main>'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `instance_eval'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `run_plugin'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/dsl/plugin.rb:98:in `run'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/dsl/plugin.rb:169:in `safe_run'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/runner.rb:84:in `run_v7_plugin'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/runner.rb:43:in `run_plugin'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/system.rb:98:in `block in run_plugins'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/system.rb:97:in `each'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/system.rb:97:in `run_plugins'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/system.rb:75:in `all_plugins'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/application.rb:90:in `run_application'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/lib/ohai/application.rb:78:in `run'
[2016-02-01T20:27:33+00:00] DEBUG: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.9.0/bin/ohai:42:in `<top (required)>'